version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    container_name: devops-app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: devops-prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: devops-grafana
