name: CD Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ~/devops-lab-service
          git pull origin master
          cd docker
          docker-compose down
          docker-compose up -d --build
